"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    method: 'all',
    func: (_req, res) => {
        return res.send({
            ChatConversationHeaderGroupDetails: true,
            ChatHeaderSearch: true,
            ChatHeaderCreateChatGroup: true,
            ChatHeaderHomeButton: false,
            ChatHeaderNotifications: true,
            ChatPlayTogether: true,
            ChatShareGameToChatFromChat: true,
            ChatTapConversationThumbnail: true,
            GamesDropDownList: true,
            GameDetailsMorePage: true,
            GameDetailsShowGlobalCounters: true,
            GameDetailsSubtitle: true,
            GameInfoList: true,
            GameInfoListDeveloper: true,
            GamePlaysAndRatings: true,
            Notifications: true,
            RecommendedGames: true,
            SearchBar: true,
            MorePageType: 'More',
            AboutPageType: 'About',
            FriendFinder: true,
            SocialLinks: true,
            SocialGroupLinks: true,
            SiteMessageBanner: true,
            UseWidthBasedFormFactorRule: false,
            UseHomePageWithAvatarAndPanel: false,
            UseBottomBar: true,
            AvatarHeaderIcon: 'LuaApp/icons/ic-back',
            AvatarEditorShowBuyRobuxOnTopBar: true,
            HomeIcon: 'LuaApp/icons/ic-roblox-close',
            ShowYouTubeAgeAlert: false,
            GameDetailsShareButton: true,
            CatalogShareButton: true,
            AccountProviderName: '',
            InviteFromAccountProvider: false,
            ShareToAccountProvider: false,
            ShareToAccountProviderTimeout: 8,
            ShowDisplayName: false,
            GamesPageCreationCenterTitle: false,
            ShowShareTargetGameCreator: true,
            SearchAutoComplete: false,
            CatalogShow3dView: true,
            CatalogCommunityCreations: true,
            CatalogPremiumCategory: true,
            ItemDetailsFullView: true,
            UseAvatarExperienceLandingPage: true,
            HomePageFriendSection: true,
            HomePageProfileLink: true,
        });
    },
};
