"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const ErrorResponders_1 = require("./ErrorResponders");
const Api_1 = require("./Api");
const express_1 = __importDefault(require("express"));
const Roblox_Util_FastLog_1 = require("./Helpers/WebHelpers/Roblox.Util/Roblox.Util.FastLog");
const DefaultApi404_1 = require("./ErrorResponders/DefaultApi404");
const aspError404_1 = require("./ErrorResponders/aspError404");
const Points_1 = require("./MiddleWare/Points");
const PointsApi_1 = require("./MiddleWare/PointsApi");
const ApiServiceIsAliveValidator_1 = require("./MiddleWare/ApiServiceIsAliveValidator");
const sslkeylog_1 = __importDefault(require("sslkeylog"));
sslkeylog_1.default.hookAll();
Roblox_Util_FastLog_1.LOGVARIABLE('GumePersistince', 6);
Roblox_Util_FastLog_1.LOGVARIABLE('TheAdminsPog', 6);
Roblox_Util_FastLog_1.LOGVARIABLE('AandBTusting', 6);
Roblox_Util_FastLog_1.LOGVARIABLE('SIMPLEPING', 6);
Roblox_Util_FastLog_1.LOGVARIABLE('Protocol77', 6);
Roblox_Util_FastLog_1.LOGVARIABLE('DataStoreV2', 7);
Roblox_Util_FastLog_1.LOGVARIABLE('DataStore', 7);
Roblox_Util_FastLog_1.LOGVARIABLE('EphemeralCountersV2', 7);
Roblox_Util_FastLog_1.LOGVARIABLE('EphemeralCounters', 7);
Roblox_Util_FastLog_1.LOGVARIABLE('Stats', 7);
Roblox_Util_FastLog_1.LOGVARIABLE('Grid', 7);
Roblox_Util_FastLog_1.LOGVARIABLE('dmp', 7);
Roblox_Util_FastLog_1.LOGVARIABLE('CsrfAPIV1', 7);
Roblox_Util_FastLog_1.LOGVARIABLE('ClientSettingsAPIV1', 7);
Roblox_Util_FastLog_1.LOGVARIABLE('WWWAuthV1', 7);
Roblox_Util_FastLog_1.LOGVARIABLE('ClientTelementry', 7);
Roblox_Util_FastLog_1.DYNAMIC_LOGVARIABLE('Tasks', 7);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_WWW'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_API'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_STATIC_CDN'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_JS'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CSS'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_IMAGES'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_SETUP_CDN'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_EPHEMERAL_COUNTERS_API'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['DEPRECATED_ROBLOX_TEMPORARY_IMAGES'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_VERSION_COMPATIBILITY_API'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CLIENT_SETTINGS_API'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_ASSET_GAME'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_EPHEMERAL_COUNTERS_VERSION_2'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_GAME_PERSISTENCE'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_DOSARREST_ORIGIN_CORP'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_MARKETPLACE_API'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_METRICS'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_AUTH'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_APIS'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_LOCALE'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_AB_TESTING'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_AB_TESTING_API'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_USERS'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_TWO_STEP_VERIFICATION'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['SIMULPONG_LATENCY_MEASUREMENTS'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CHAT'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CONTACTS'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_NOTIFICATIONS'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_ACCOUNT_SETTINGS'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_ADS'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_TRADES'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_FRIENDS'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_PRIVATE_MESSAGES'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_ECONOMY'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_GAMES'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_REAL_TIME'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_THUMB_NAILS'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_PRESENCE'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_GROUPS'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_ACCOUNT_INFORMATION'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_BADGES'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_DEVELOPER_FORUM'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_PREMIUM_FEATURES'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CLIENT_SETTINGS'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CLIENT_SETTINGS_CDN'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_AD_CONFIGURATION'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CLIENT_TELEMENTRY'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_ASSET_DELIVERY'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_AVATAR'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_BILLING'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CATALOG'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CDN_PROVIDERS'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CHAT_MODERATION'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CONTENT_STORE'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_DEVELOP'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_DISCUSSIONS'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_ECONOMY_CREATOR_STATS'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_ENGAGEMENT_PAYOUTS'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_FOLLOWINGS'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_GAME_INTERNATIONALIZATION'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_GAME_JOIN'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_GROUPS_MODERATION'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_INVENTORY'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_ITEM_CONFIGURATION'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_LOCALIZATION_TABLES'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_POINTS'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_PUBLISH'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_PUNISHMENTS'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_SHARE'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_TEXT_FILTER'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_THEMES'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_THUMBNAILS_RESIZER'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_TRANSLATION_ROLES'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_TRANSLATIONS'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_USER_MODERATION'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_VOICE'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_FILES_API'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['SIMULPONG_ROBLOX_TEAM_CITY'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ADMIN_WEB_SITE'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['COM_APIS'], 6);
Roblox_Util_FastLog_1.SYNCHRONIZED_LOGVARIABLE(Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_POINTS_API'], 6);
Roblox_Util_FastLog_1.FASTFLAGVARIABLE('RequireGlobalHTTPS', true);
(async () => {
    try {
        await Api_1.RobloxLegacy.Api.Helpers.Helpers.Sessions.ClearCachedSessions();
        const ROBLOX_WWW_SERVER = express_1.default();
        const ROBLOX_STATIC_CDN_SERVER = express_1.default();
        const ROBLOX_JS_SERVER = express_1.default();
        const ROBLOX_CSS_SERVER = express_1.default();
        const ROBLOX_IMAGES_SERVER = express_1.default();
        const ROBLOX_SETUP_CDN_SERVER = express_1.default();
        const ROBLOX_API_SERVER = express_1.default();
        const ROBLOX_EPHEMERAL_COUNTERS_API_SERVER = express_1.default();
        const ROBLOX_EPHEMERAL_COUNTERS_VERSION_2_SERVER = express_1.default();
        const DEPRECATED_ROBLOX_TEMPORARY_IMAGES_SERVER = express_1.default();
        const ROBLOX_VERSION_COMPATIBILITY_API_SERVER = express_1.default();
        const ROBLOX_CLIENT_SETTINGS_API_SERVER = express_1.default();
        const ROBLOX_ASSET_GAME_SERVER = express_1.default();
        const ROBLOX_GAME_PERSISTENCE_SERVER = express_1.default();
        const ROBLOX_DOSARREST_ORIGIN_CORP_SERVER = express_1.default();
        const ROBLOX_MARKETPLACE_API_SERVER = express_1.default();
        const ROBLOX_METRICS_SERVER = express_1.default();
        const ROBLOX_APIS_SERVER = express_1.default();
        const ROBLOX_LOCALE_SERVER = express_1.default();
        const ROBLOX_AUTH_SERVER = express_1.default();
        const ROBLOX_AB_TESTING_SERVER = express_1.default();
        const ROBLOX_AB_TESTING_API_SERVER = express_1.default();
        const ROBLOX_USERS_SERVER = express_1.default();
        const ROBLOX_TWO_STEP_VERIFICATION_SERVER = express_1.default();
        const SIMULPONG_LATENCY_MEASUREMENTS_SERVER = express_1.default();
        const ROBLOX_CHAT_SERVER = express_1.default();
        const ROBLOX_CONTACTS_SERVER = express_1.default();
        const ROBLOX_NOTIFICATIONS_SERVER = express_1.default();
        const ROBLOX_ACCOUNT_SETTINGS_SERVER = express_1.default();
        const ROBLOX_ADS_SERVER = express_1.default();
        const ROBLOX_TRADES_SERVER = express_1.default();
        const ROBLOX_FRIENDS_SERVER = express_1.default();
        const ROBLOX_PRIVATE_MESSAGES_SERVER = express_1.default();
        const ROBLOX_ECONOMY_SERVER = express_1.default();
        const ROBLOX_GAMES_SERVER = express_1.default();
        const ROBLOX_REAL_TIME_SERVER = express_1.default();
        const ROBLOX_THUMBNAILS_SERVER = express_1.default();
        const ROBLOX_PRESENCE_SERVER = express_1.default();
        const ROBLOX_GROUPS_SERVER = express_1.default();
        const ROBLOX_ACCOUNT_INFORMATION_SERVER = express_1.default();
        const ROBLOX_BADGES_SERVER = express_1.default();
        const ROBLOX_DEVELOPER_FORUM_SERVER = express_1.default();
        const ROBLOX_PREMIUM_FEATURES_SERVER = express_1.default();
        const ROBLOX_CLIENT_SETTINGS_SERVER = express_1.default();
        const ROBLOX_CLIENT_SETTINGS_CDN_SERVER = express_1.default();
        const ROBLOX_AD_CONFIGURATION_SERVER = express_1.default();
        const ROBLOX_CLIENT_TELEMENTRY_SERVER = express_1.default();
        const ROBLOX_ASSET_DELIVERY_SERVER = express_1.default();
        const ROBLOX_AVATAR_SERVER = express_1.default();
        const ROBLOX_BILLING_SERVER = express_1.default();
        const ROBLOX_CATALOG_SERVER = express_1.default();
        const ROBLOX_CDN_PROVIDERS_SERVER = express_1.default();
        const ROBLOX_CHAT_MODERATION_SERVER = express_1.default();
        const ROBLOX_CONTENT_STORE_SERVER = express_1.default();
        const ROBLOX_DEVELOP_SERVER = express_1.default();
        const ROBLOX_DISCUSSIONS_SERVER = express_1.default();
        const ROBLOX_ECONOMY_CREATOR_STATS_SERVER = express_1.default();
        const ROBLOX_ENGAGEMENT_PAYOUTS_SERVER = express_1.default();
        const ROBLOX_FOLLOWINGS_SERVER = express_1.default();
        const ROBLOX_GAME_INTERNATIONALIZATION_SERVER = express_1.default();
        const ROBLOX_GAME_JOIN_SERVER = express_1.default();
        const ROBLOX_GROUPS_MODERATION_SERVER = express_1.default();
        const ROBLOX_INVENTORY_SERVER = express_1.default();
        const ROBLOX_ITEM_CONFIGURATION_SERVER = express_1.default();
        const ROBLOX_LOCALIZATION_TABLES_SERVER = express_1.default();
        const ROBLOX_POINTS_SERVER = express_1.default();
        const ROBLOX_PUBLISH_SERVER = express_1.default();
        const ROBLOX_PUNISHMENTS_SERVER = express_1.default();
        const ROBLOX_SHARE_SERVER = express_1.default();
        const ROBLOX_TEXT_FILTER_SERVER = express_1.default();
        const ROBLOX_THEMES_SERVER = express_1.default();
        const ROBLOX_THUMBNAILS_RESIZER_SERVER = express_1.default();
        const ROBLOX_TRANSLATION_ROLES_SERVER = express_1.default();
        const ROBLOX_TRANSLATIONS_SERVER = express_1.default();
        const ROBLOX_USER_MODERATION = express_1.default();
        const ROBLOX_VOICE_SERVER = express_1.default();
        const ROBLOX_FILES_API_SERVER = express_1.default();
        const SIMULPONG_ROBLOX_TEAM_CITY_SERVER = express_1.default();
        const ADMIN_WEB_SITE_SERVER = express_1.default();
        const COM_APIS_SERVER = express_1.default();
        const ROBLOX_POINTS_API_SERVER = express_1.default();
        ROBLOX_WWW_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_STATIC_CDN_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_JS_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_CSS_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_IMAGES_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_SETUP_CDN_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_API_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_EPHEMERAL_COUNTERS_API_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_EPHEMERAL_COUNTERS_VERSION_2_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        DEPRECATED_ROBLOX_TEMPORARY_IMAGES_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_VERSION_COMPATIBILITY_API_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_CLIENT_SETTINGS_API_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_ASSET_GAME_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_GAME_PERSISTENCE_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GAMEPERSISTENCE);
        ROBLOX_DOSARREST_ORIGIN_CORP_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_MARKETPLACE_API_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_METRICS_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_APIS_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.KESTREL);
        ROBLOX_LOCALE_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_AUTH_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_AB_TESTING_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.ABTESTING);
        ROBLOX_AB_TESTING_API_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.ABTESTING);
        ROBLOX_USERS_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_TWO_STEP_VERIFICATION_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        SIMULPONG_LATENCY_MEASUREMENTS_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.SIMULPONG);
        ROBLOX_CHAT_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_CONTACTS_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_NOTIFICATIONS_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_ACCOUNT_SETTINGS_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_ADS_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_TRADES_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_FRIENDS_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_PRIVATE_MESSAGES_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_ECONOMY_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_GAMES_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_REAL_TIME_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_THUMBNAILS_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_PRESENCE_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_GROUPS_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_ACCOUNT_INFORMATION_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_BADGES_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_DEVELOPER_FORUM_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_PREMIUM_FEATURES_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_CLIENT_SETTINGS_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_CLIENT_SETTINGS_CDN_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_AD_CONFIGURATION_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_CLIENT_TELEMENTRY_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_ASSET_DELIVERY_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_AVATAR_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_BILLING_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_CATALOG_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_CDN_PROVIDERS_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_CHAT_MODERATION_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_CONTENT_STORE_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_DEVELOP_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_DISCUSSIONS_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_ECONOMY_CREATOR_STATS_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_ENGAGEMENT_PAYOUTS_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_FOLLOWINGS_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_GAME_INTERNATIONALIZATION_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_GAME_JOIN_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_GROUPS_MODERATION_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_INVENTORY_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_ITEM_CONFIGURATION_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_LOCALIZATION_TABLES_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_POINTS_SERVER.use(ApiServiceIsAliveValidator_1.ApiServiceIsAliveValidator, Points_1.Points);
        ROBLOX_PUNISHMENTS_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_SHARE_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_TEXT_FILTER_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_THEMES_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_THUMBNAILS_RESIZER_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_TRANSLATION_ROLES_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_TRANSLATIONS_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_USER_MODERATION.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_PUBLISH_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_VOICE_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        ROBLOX_FILES_API_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.GLOBAL);
        SIMULPONG_ROBLOX_TEAM_CITY_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.SIMULPONG);
        ADMIN_WEB_SITE_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.ADMINWEBSITE);
        COM_APIS_SERVER.use(Api_1.RobloxLegacy.Api.Helpers.BeforeNext.Middle.KESTREL);
        ROBLOX_POINTS_API_SERVER.use(PointsApi_1.PointsApi);
        ROBLOX_APIS_SERVER.set('views', Api_1.RobloxLegacy.Api.Constants.RobloxDirectories.__iBaseDirectory + '\\TestViews');
        ROBLOX_APIS_SERVER.set('view engine', 'jsx');
        ROBLOX_APIS_SERVER.engine('jsx', require('express-react-views').createEngine());
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_STATIC_CDN_SERVER, '\\StaticPages\\Roblox.StaticCDN', '\\Assemblies\\Controllers\\Roblox.StaticCDN', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_STATIC_CDN']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_JS_SERVER, '\\StaticPages\\Roblox.JS.Distribution', '\\Assemblies\\Controllers\\Roblox.JS', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_JS']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_CSS_SERVER, '\\StaticPages\\Roblox.CSS', '\\Assemblies\\Controllers\\Roblox.CSS', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CSS']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_IMAGES_SERVER, '\\StaticPages\\Roblox.Images', '\\Assemblies\\Controllers\\Roblox.Images', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_IMAGES']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_API_SERVER, '\\StaticPages\\Roblox.Api', '\\Assemblies\\Controllers\\Roblox.Api', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_API']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_SETUP_CDN_SERVER, '\\StaticPages\\Roblox.SetupCDN', '\\Assemblies\\Controllers\\Roblox.SetupCDN', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_SETUP_CDN']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_WWW_SERVER, '\\StaticPages\\Roblox.WWWRoot', '\\Assemblies\\Controllers\\Roblox.WWWRoot', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_WWW'], false));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_EPHEMERAL_COUNTERS_API_SERVER, '\\StaticPages\\Roblox.EphemeralCountersApi', '\\Assemblies\\Controllers\\Roblox.EphemeralCountersApi', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_EPHEMERAL_COUNTERS_API']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_EPHEMERAL_COUNTERS_VERSION_2_SERVER, '\\StaticPages\\Roblox.EphemeralCounters.Version_2', '\\Assemblies\\Controllers\\Roblox.EphemeralCounters.Version_2', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_EPHEMERAL_COUNTERS_VERSION_2']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(DEPRECATED_ROBLOX_TEMPORARY_IMAGES_SERVER, '\\StaticPages\\Roblox.TemporaryImages', '\\Assemblies\\Controllers\\Roblox.TemporaryImages', Api_1.RobloxLegacy.Api.Constants.URLS['DEPRECATED_ROBLOX_TEMPORARY_IMAGES']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_VERSION_COMPATIBILITY_API_SERVER, '\\StaticPages\\Roblox.VersionCompatibilityApi', '\\Assemblies\\Controllers\\Roblox.VersionCompatibilityApi', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_VERSION_COMPATIBILITY_API']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_CLIENT_SETTINGS_API_SERVER, '\\StaticPages\\Roblox.ClientSettingsApi', '\\Assemblies\\Controllers\\Roblox.ClientSettingsApi', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CLIENT_SETTINGS_API']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_ASSET_GAME_SERVER, '\\StaticPages\\Roblox.AssetGame', '\\Assemblies\\Controllers\\Roblox.AssetGame', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_ASSET_GAME']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_GAME_PERSISTENCE_SERVER, '\\StaticPages\\Roblox.GamePersistence', '\\Assemblies\\Controllers\\Roblox.GamePersistence', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_GAME_PERSISTENCE']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_DOSARREST_ORIGIN_CORP_SERVER, '\\StaticPages\\Roblox.DOSArrest', '\\Assemblies\\Controllers\\Roblox.DOSArrest', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_DOSARREST_ORIGIN_CORP']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_MARKETPLACE_API_SERVER, '\\StaticPages\\Roblox.MarketPlaceApi', '\\Assemblies\\Controllers\\Roblox.MarketPlaceApi', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_MARKETPLACE_API']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_METRICS_SERVER, '\\StaticPages\\Roblox.Metrics', '\\Assemblies\\Controllers\\Roblox.Metrics', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_METRICS']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_AUTH_SERVER, '\\StaticPages\\Roblox.Auth', '\\Assemblies\\Controllers\\Roblox.Auth', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_AUTH']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_APIS_SERVER, '\\StaticPages\\Roblox.Apis', '\\Assemblies\\Controllers\\Roblox.Apis', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_APIS']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_LOCALE_SERVER, '\\StaticPages\\Roblox.Locale', '\\Assemblies\\Controllers\\Roblox.Locale', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_LOCALE']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_AB_TESTING_SERVER, '\\StaticPages\\Roblox.AbTesting', '\\Assemblies\\Controllers\\Roblox.AbTesting', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_AB_TESTING']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_AB_TESTING_API_SERVER, '\\StaticPages\\Roblox.AbTestingApi', '\\Assemblies\\Controllers\\Roblox.AbTestingApi', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_AB_TESTING_API']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_USERS_SERVER, '\\StaticPages\\Roblox.Users', '\\Assemblies\\Controllers\\Roblox.Users', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_USERS']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_TWO_STEP_VERIFICATION_SERVER, '\\StaticPages\\Roblox.TwoStepVerification', '\\Assemblies\\Controllers\\Roblox.TwoStepVerification', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_TWO_STEP_VERIFICATION']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(SIMULPONG_LATENCY_MEASUREMENTS_SERVER, '\\StaticPages\\SimulPong.LatencyMeasurements', '\\Assemblies\\Controllers\\SimulPong.LatencyMeasurements', Api_1.RobloxLegacy.Api.Constants.URLS['SIMULPONG_LATENCY_MEASUREMENTS']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_CHAT_SERVER, '\\StaticPages\\Roblox.Chat', '\\Assemblies\\Controllers\\Roblox.Chat', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CHAT']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_CONTACTS_SERVER, '\\StaticPages\\Roblox.Contacts', '\\Assemblies\\Controllers\\Roblox.Contacts', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CONTACTS']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_NOTIFICATIONS_SERVER, '\\StaticPages\\Roblox.Notifications', '\\Assemblies\\Controllers\\Roblox.Notifications', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_NOTIFICATIONS']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_ACCOUNT_SETTINGS_SERVER, '\\StaticPages\\Roblox.AccountSettings', '\\Assemblies\\Controllers\\Roblox.AccountSettings', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_ACCOUNT_SETTINGS']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_ADS_SERVER, '\\StaticPages\\Roblox.Ads', '\\Assemblies\\Controllers\\Roblox.Ads', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_ADS']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_TRADES_SERVER, '\\StaticPages\\Roblox.Trades', '\\Assemblies\\Controllers\\Roblox.Trades', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_TRADES']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_FRIENDS_SERVER, '\\StaticPages\\Roblox.Friends', '\\Assemblies\\Controllers\\Roblox.Friends', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_FRIENDS']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_PRIVATE_MESSAGES_SERVER, '\\StaticPages\\Roblox.PrivateMessages', '\\Assemblies\\Controllers\\Roblox.PrivateMessages', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_PRIVATE_MESSAGES']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_ECONOMY_SERVER, '\\StaticPages\\Roblox.Economy', '\\Assemblies\\Controllers\\Roblox.Economy', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_ECONOMY']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_GAMES_SERVER, '\\StaticPages\\Roblox.Games', '\\Assemblies\\Controllers\\Roblox.Games', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_GAMES']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_REAL_TIME_SERVER, '\\StaticPages\\Roblox.RealTime', '\\Assemblies\\Controllers\\Roblox.RealTime', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_REAL_TIME']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_THUMBNAILS_SERVER, '\\StaticPages\\Roblox.ThumbNails', '\\Assemblies\\Controllers\\Roblox.ThumbNails', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_THUMB_NAILS']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_PRESENCE_SERVER, '\\StaticPages\\Roblox.Presence', '\\Assemblies\\Controllers\\Roblox.Presence', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_PRESENCE']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_GROUPS_SERVER, '\\StaticPages\\Roblox.Groups', '\\Assemblies\\Controllers\\Roblox.Groups', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_GROUPS']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_ACCOUNT_INFORMATION_SERVER, '\\StaticPages\\Roblox.AccountInformation', '\\Assemblies\\Controllers\\Roblox.AccountInformation', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_ACCOUNT_INFORMATION']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_BADGES_SERVER, '\\StaticPages\\Roblox.Badges', '\\Assemblies\\Controllers\\Roblox.Badges', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_BADGES']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_DEVELOPER_FORUM_SERVER, '\\StaticPages\\Roblox.DeveloperForum', '\\Assemblies\\Controllers\\Roblox.DeveloperForum', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_DEVELOPER_FORUM']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_PREMIUM_FEATURES_SERVER, '\\StaticPages\\Roblox.PremiumFeatures', '\\Assemblies\\Controllers\\Roblox.PremiumFeatures', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_PREMIUM_FEATURES']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_CLIENT_SETTINGS_SERVER, '\\StaticPages\\Roblox.ClientSettings', '\\Assemblies\\Controllers\\Roblox.ClientSettings', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CLIENT_SETTINGS']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_CLIENT_SETTINGS_CDN_SERVER, '\\StaticPages\\Roblox.ClientSettingsCDN', '\\Assemblies\\Controllers\\Roblox.ClientSettingsCDN', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CLIENT_SETTINGS_CDN']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_AD_CONFIGURATION_SERVER, '\\StaticPages\\Roblox.AdConfiguration', '\\Assemblies\\Controllers\\Roblox.AdConfiguration', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_AD_CONFIGURATION']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_CLIENT_TELEMENTRY_SERVER, '\\StaticPages\\Roblox.ClientTelementry', '\\Assemblies\\Controllers\\Roblox.ClientTelementry', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CLIENT_TELEMENTRY']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_ASSET_DELIVERY_SERVER, '\\StaticPages\\Roblox.AssetDelivery', '\\Assemblies\\Controllers\\Roblox.AssetDelivery', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_ASSET_DELIVERY']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_AVATAR_SERVER, '\\StaticPages\\Roblox.Avatar', '\\Assemblies\\Controllers\\Roblox.Avatar', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_AVATAR']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_BILLING_SERVER, '\\StaticPages\\Roblox.Billing', '\\Assemblies\\Controllers\\Roblox.Billing', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_BILLING']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_CATALOG_SERVER, '\\StaticPages\\Roblox.Catalog', '\\Assemblies\\Controllers\\Roblox.Catalog', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CATALOG']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_CDN_PROVIDERS_SERVER, '\\StaticPages\\Roblox.CdnProviders', '\\Assemblies\\Controllers\\Roblox.CdnProviders', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CDN_PROVIDERS']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_CHAT_MODERATION_SERVER, '\\StaticPages\\Roblox.ChatModeration', '\\Assemblies\\Controllers\\Roblox.ChatModeration', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CHAT_MODERATION']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_CONTENT_STORE_SERVER, '\\StaticPages\\Roblox.ContentStore', '\\Assemblies\\Controllers\\Roblox.ContentStore', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CONTENT_STORE']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_DEVELOP_SERVER, '\\StaticPages\\Roblox.Develop', '\\Assemblies\\Controllers\\Roblox.Develop', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_DEVELOP']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_DISCUSSIONS_SERVER, '\\StaticPages\\Roblox.Discussions', '\\Assemblies\\Controllers\\Roblox.Discussions', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_DISCUSSIONS']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_ECONOMY_CREATOR_STATS_SERVER, '\\StaticPages\\Roblox.EconomyCreatorStats', '\\Assemblies\\Controllers\\Roblox.EconomyCreatorStats', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_ECONOMY_CREATOR_STATS']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_ENGAGEMENT_PAYOUTS_SERVER, '\\StaticPages\\Roblox.EngagementPayouts', '\\Assemblies\\Controllers\\Roblox.EngagementPayouts', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_ENGAGEMENT_PAYOUTS']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_FOLLOWINGS_SERVER, '\\StaticPages\\Roblox.Followings', '\\Assemblies\\Controllers\\Roblox.Followings', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_FOLLOWINGS']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_GAME_INTERNATIONALIZATION_SERVER, '\\StaticPages\\Roblox.GameInternationalization', '\\Assemblies\\Controllers\\Roblox.GameInternationalization', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_GAME_INTERNATIONALIZATION']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_GAME_JOIN_SERVER, '\\StaticPages\\Roblox.GameJoin', '\\Assemblies\\Controllers\\Roblox.GameJoin', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_GAME_JOIN']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_GROUPS_MODERATION_SERVER, '\\StaticPages\\Roblox.GroupsModeration', '\\Assemblies\\Controllers\\Roblox.GroupsModeration', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_GROUPS_MODERATION']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_INVENTORY_SERVER, '\\StaticPages\\Roblox.Inventory', '\\Assemblies\\Controllers\\Roblox.Inventory', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_AD_CONFIGURATION']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_ITEM_CONFIGURATION_SERVER, '\\StaticPages\\Roblox.ItemConfiguration', '\\Assemblies\\Controllers\\Roblox.ItemConfiguration', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_ITEM_CONFIGURATION']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_AD_CONFIGURATION_SERVER, '\\StaticPages\\Roblox.AdConfiguration', '\\Assemblies\\Controllers\\Roblox.AdConfiguration', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_AD_CONFIGURATION']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_LOCALIZATION_TABLES_SERVER, '\\StaticPages\\Roblox.LocalizationTables', '\\Assemblies\\Controllers\\Roblox.LocalizationTables', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_LOCALIZATION_TABLES']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_POINTS_SERVER, '\\StaticPages\\Roblox.Points', '\\Assemblies\\Controllers\\Roblox.Points', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_POINTS']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_PUBLISH_SERVER, '\\StaticPages\\Roblox.Publish', '\\Assemblies\\Controllers\\Roblox.Publish', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_PUBLISH']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_PUNISHMENTS_SERVER, '\\StaticPages\\Roblox.Punishments', '\\Assemblies\\Controllers\\Roblox.Punishments', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_PUNISHMENTS']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_SHARE_SERVER, '\\StaticPages\\Roblox.Share', '\\Assemblies\\Controllers\\Roblox.Share', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_SHARE']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_TEXT_FILTER_SERVER, '\\StaticPages\\Roblox.TextFilter', '\\Assemblies\\Controllers\\Roblox.TextFilter', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_TEXT_FILTER']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_THEMES_SERVER, '\\StaticPages\\Roblox.Themes', '\\Assemblies\\Controllers\\Roblox.Themes', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_THEMES']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_THUMBNAILS_RESIZER_SERVER, '\\StaticPages\\Roblox.ThumbnailsResizer', '\\Assemblies\\Controllers\\Roblox.ThumbnailsResizer', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_THUMBNAILS_RESIZER']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_TRANSLATION_ROLES_SERVER, '\\StaticPages\\Roblox.TranslationRoles', '\\Assemblies\\Controllers\\Roblox.TranslationRoles', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_TRANSLATION_ROLES']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_TRANSLATIONS_SERVER, '\\StaticPages\\Roblox.Translations', '\\Assemblies\\Controllers\\Roblox.Translations', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_TRANSLATIONS']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_USER_MODERATION, '\\StaticPages\\Roblox.UserModeration', '\\Assemblies\\Controllers\\Roblox.UserModeration', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_USER_MODERATION']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_VOICE_SERVER, '\\StaticPages\\Roblox.Voice', '\\Assemblies\\Controllers\\Roblox.Voice', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_VOICE']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_FILES_API_SERVER, '\\StaticPages\\Roblox.FilesApi', '\\Assemblies\\Controllers\\Roblox.FilesApi', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_FILES_API']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(SIMULPONG_ROBLOX_TEAM_CITY_SERVER, '\\StaticPages\\SimulPong.TeamCity', '\\Assemblies\\Controllers\\SimulPong.TeamCity', Api_1.RobloxLegacy.Api.Constants.URLS['SIMULPONG_ROBLOX_TEAM_CITY']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ADMIN_WEB_SITE_SERVER, '\\StaticPages\\AdminWebsite', '\\Assemblies\\Controllers\\AdminWebsite', Api_1.RobloxLegacy.Api.Constants.URLS['ADMIN_WEB_SITE']));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(COM_APIS_SERVER, '\\StaticPages\\Com.Apis', '\\Assemblies\\Controllers\\Com.Apis', Api_1.RobloxLegacy.Api.Constants.URLS['COM_APIS'], false, true));
        await Api_1.RobloxLegacy.Api.Library.IStartup.Configure(Api_1.RobloxLegacy.Api.Helpers.Config.CONFIG(ROBLOX_POINTS_API_SERVER, '\\StaticPages\\Roblox.PointsApi', '\\Assemblies\\Controllers\\Roblox.PointsApi', Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_POINTS_API']));
        ROBLOX_API_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_STATIC_CDN_SERVER.use(ErrorResponders_1.ROBLOX_404_STATIC_CDN);
        ROBLOX_JS_SERVER.use(ErrorResponders_1.ROBLOX_404_JS);
        ROBLOX_CSS_SERVER.use(ErrorResponders_1.ROBLOX_404_CSS);
        ROBLOX_IMAGES_SERVER.use(ErrorResponders_1.ROBLOX_404_IMAGES);
        ROBLOX_SETUP_CDN_SERVER.use(ErrorResponders_1.ROBLOX_404_SETUP_CDN);
        ROBLOX_WWW_SERVER.use(ErrorResponders_1.ROBLOX_404_WWW);
        ROBLOX_EPHEMERAL_COUNTERS_API_SERVER.use(ErrorResponders_1.ROBLOX_404_EPHEMERAL_COUNTERS);
        ROBLOX_EPHEMERAL_COUNTERS_VERSION_2_SERVER.use(ErrorResponders_1.ROBLOX_404_EPHEMERAL_COUNTERS);
        DEPRECATED_ROBLOX_TEMPORARY_IMAGES_SERVER.use(ErrorResponders_1.DEPRECATED_404_TEMPORARY_IMAGES);
        ROBLOX_VERSION_COMPATIBILITY_API_SERVER.use(ErrorResponders_1.ROBLOX_404_EPHEMERAL_COUNTERS);
        ROBLOX_CLIENT_SETTINGS_API_SERVER.use(ErrorResponders_1.ROBLOX_404_EPHEMERAL_COUNTERS);
        ROBLOX_ASSET_GAME_SERVER.use(ErrorResponders_1.ROBLOX_404_EPHEMERAL_COUNTERS);
        ROBLOX_GAME_PERSISTENCE_SERVER.use(ErrorResponders_1.ROBLOX_404_EPHEMERAL_COUNTERS);
        ROBLOX_DOSARREST_ORIGIN_CORP_SERVER.use(ErrorResponders_1.ROBLOX_404_DOSARREST_ORIGIN_CORP);
        ROBLOX_MARKETPLACE_API_SERVER.use(ErrorResponders_1.ROBLOX_404_EPHEMERAL_COUNTERS);
        ROBLOX_METRICS_SERVER.use(ErrorResponders_1.ROBLOX_404_EPHEMERAL_COUNTERS);
        ROBLOX_AUTH_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_APIS_SERVER.use(ErrorResponders_1.Kestrel_404);
        ROBLOX_LOCALE_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_AB_TESTING_SERVER.use(ErrorResponders_1.ROBLOX_404_AB_TESTING);
        ROBLOX_AB_TESTING_API_SERVER.use(ErrorResponders_1.ROBLOX_404_EPHEMERAL_COUNTERS);
        ROBLOX_USERS_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        SIMULPONG_LATENCY_MEASUREMENTS_SERVER.use(ErrorResponders_1.SIMULPONG_404);
        ROBLOX_CHAT_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_CONTACTS_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_NOTIFICATIONS_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_ACCOUNT_SETTINGS_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_ADS_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_TRADES_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_FRIENDS_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_PRIVATE_MESSAGES_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_ECONOMY_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_GAMES_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_REAL_TIME_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_THUMBNAILS_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_PRESENCE_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_GROUPS_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_ACCOUNT_INFORMATION_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_BADGES_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_DEVELOPER_FORUM_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_PREMIUM_FEATURES_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_CLIENT_SETTINGS_SERVER.use(ErrorResponders_1.ROBLOX_404_EPHEMERAL_COUNTERS);
        ROBLOX_CLIENT_SETTINGS_CDN_SERVER.use(ErrorResponders_1.ROBLOX_404_EPHEMERAL_COUNTERS);
        ROBLOX_AD_CONFIGURATION_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_CLIENT_TELEMENTRY_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_ASSET_DELIVERY_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_AVATAR_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_BILLING_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_CATALOG_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_CDN_PROVIDERS_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_CHAT_MODERATION_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_CONTENT_STORE_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_DEVELOP_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_DISCUSSIONS_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_ECONOMY_CREATOR_STATS_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_ENGAGEMENT_PAYOUTS_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_FOLLOWINGS_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_GAME_INTERNATIONALIZATION_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_GAME_JOIN_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_GROUPS_MODERATION_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_INVENTORY_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_ITEM_CONFIGURATION_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_LOCALIZATION_TABLES_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_POINTS_SERVER.use(DefaultApi404_1.DefaultApi404);
        ROBLOX_PUNISHMENTS_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_SHARE_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_TEXT_FILTER_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_THEMES_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_THUMBNAILS_RESIZER_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_TRANSLATION_ROLES_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_TRANSLATIONS_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_USER_MODERATION.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_PUBLISH_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_VOICE_SERVER.use(ErrorResponders_1.ROBLOX_404_API);
        ROBLOX_FILES_API_SERVER.use(ErrorResponders_1.ROBLOX_404_EPHEMERAL_COUNTERS);
        SIMULPONG_ROBLOX_TEAM_CITY_SERVER.use(ErrorResponders_1.SIMULPONG_404);
        ADMIN_WEB_SITE_SERVER.use(ErrorResponders_1.ROBLOX_404_EPHEMERAL_COUNTERS);
        COM_APIS_SERVER.use(ErrorResponders_1.Kestrel_404);
        ROBLOX_POINTS_API_SERVER.use(aspError404_1.DefaultAsp404);
        await (async () => {
            try {
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_IMAGES_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_IMAGES']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_WWW_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_WWW']);
                const [ROBLOX_API_HTTP, ROBLOX_API_HTTPS] = Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_API_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_API']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_STATIC_CDN_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_STATIC_CDN']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_JS_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_JS']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_CSS_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CSS']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_SETUP_CDN_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_SETUP_CDN']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(DEPRECATED_ROBLOX_TEMPORARY_IMAGES_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['DEPRECATED_ROBLOX_TEMPORARY_IMAGES']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_VERSION_COMPATIBILITY_API_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_VERSION_COMPATIBILITY_API']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_CLIENT_SETTINGS_API_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CLIENT_SETTINGS_API']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_ASSET_GAME_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_ASSET_GAME']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_EPHEMERAL_COUNTERS_API_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_EPHEMERAL_COUNTERS_API']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_EPHEMERAL_COUNTERS_VERSION_2_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_EPHEMERAL_COUNTERS_VERSION_2']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_GAME_PERSISTENCE_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_GAME_PERSISTENCE']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_DOSARREST_ORIGIN_CORP_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_DOSARREST_ORIGIN_CORP']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_METRICS_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_METRICS']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_AUTH_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_AUTH']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_APIS_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_APIS']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_LOCALE_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_LOCALE']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_MARKETPLACE_API_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_MARKETPLACE_API']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_AB_TESTING_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_AB_TESTING']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_AB_TESTING_API_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_AB_TESTING_API']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_USERS_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_USERS']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_TWO_STEP_VERIFICATION_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_TWO_STEP_VERIFICATION']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(SIMULPONG_LATENCY_MEASUREMENTS_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['SIMULPONG_LATENCY_MEASUREMENTS']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_CHAT_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CHAT']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_CONTACTS_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CONTACTS']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_NOTIFICATIONS_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_NOTIFICATIONS']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_ACCOUNT_SETTINGS_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_ACCOUNT_SETTINGS']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_ADS_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_ADS']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_TRADES_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_TRADES']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_FRIENDS_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_FRIENDS']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_PRIVATE_MESSAGES_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_PRIVATE_MESSAGES']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_ECONOMY_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_ECONOMY']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_GAMES_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_GAMES']);
                const [ROBLOX_REAL_TIME_HTTP, ROBLOX_REAL_TIME_HTTPS] = Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_REAL_TIME_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_REAL_TIME']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_THUMBNAILS_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_THUMB_NAILS']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_PRESENCE_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_PRESENCE']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_GROUPS_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_GROUPS']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_ACCOUNT_INFORMATION_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_ACCOUNT_INFORMATION']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_BADGES_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_BADGES']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_DEVELOPER_FORUM_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_DEVELOPER_FORUM']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_PREMIUM_FEATURES_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_PREMIUM_FEATURES']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_CLIENT_SETTINGS_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CLIENT_SETTINGS']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_CLIENT_SETTINGS_CDN_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CLIENT_SETTINGS_CDN']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_AD_CONFIGURATION_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_AD_CONFIGURATION']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_CLIENT_TELEMENTRY_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CLIENT_TELEMENTRY']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_ASSET_DELIVERY_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_ASSET_DELIVERY']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_AVATAR_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_AVATAR']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_BILLING_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_BILLING']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_CATALOG_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CATALOG']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_CDN_PROVIDERS_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CDN_PROVIDERS']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_CHAT_MODERATION_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CHAT_MODERATION']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_CONTENT_STORE_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_CONTENT_STORE']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_DEVELOP_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_DEVELOP']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_DISCUSSIONS_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_DISCUSSIONS']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_ECONOMY_CREATOR_STATS_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_ECONOMY_CREATOR_STATS']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_ENGAGEMENT_PAYOUTS_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_ENGAGEMENT_PAYOUTS']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_FOLLOWINGS_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_FOLLOWINGS']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_GAME_INTERNATIONALIZATION_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_GAME_INTERNATIONALIZATION']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_GAME_JOIN_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_GAME_JOIN']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_GROUPS_MODERATION_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_GROUPS_MODERATION']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_INVENTORY_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_INVENTORY']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_ITEM_CONFIGURATION_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_ITEM_CONFIGURATION']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_LOCALIZATION_TABLES_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_LOCALIZATION_TABLES']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_POINTS_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_POINTS']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_PUBLISH_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_PUBLISH']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_PUNISHMENTS_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_PUNISHMENTS']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_SHARE_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_SHARE']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_TEXT_FILTER_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_TEXT_FILTER']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_THEMES_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_THEMES']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_THUMBNAILS_RESIZER_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_THUMBNAILS_RESIZER']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_TRANSLATION_ROLES_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_TRANSLATION_ROLES']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_TRANSLATIONS_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_TRANSLATIONS']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_USER_MODERATION, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_USER_MODERATION']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_VOICE_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_VOICE']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_FILES_API_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_FILES_API']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(SIMULPONG_ROBLOX_TEAM_CITY_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['SIMULPONG_ROBLOX_TEAM_CITY']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ADMIN_WEB_SITE_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ADMIN_WEB_SITE']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(COM_APIS_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['COM_APIS']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_Starter(ROBLOX_POINTS_API_SERVER, Api_1.RobloxLegacy.Api.Constants.URLS['ROBLOX_POINTS_API']);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_SignalR_Config_Helper(ROBLOX_API_HTTP, ROBLOX_API_HTTPS, '\\Assemblies\\WebSockets\\Roblox.Api', Api_1.RobloxLegacy.Api.Constants.URLS.ROBLOX_API);
                Api_1.RobloxLegacy.Api.Helpers.Web.Util.ROBLOX_SignalR_Config_Helper(ROBLOX_REAL_TIME_HTTP, ROBLOX_REAL_TIME_HTTPS, '\\Assemblies\\WebSockets\\Roblox.RealTime', Api_1.RobloxLegacy.Api.Constants.URLS.ROBLOX_REAL_TIME);
                Roblox_Util_FastLog_1.FASTLOG1F(Roblox_Util_FastLog_1.DFLog('Tasks'), '[DFLog::Tasks] There are %d Services running...', Object.keys(Api_1.RobloxLegacy.Api.Constants.URLS).length);
            }
            catch (e) {
                return Roblox_Util_FastLog_1.FASTLOG2(Roblox_Util_FastLog_1.DFLog('Tasks'), `[DFLog::Tasks] Error: %s, Stack Trace: %s`, e.message, e.stack);
            }
        })();
    }
    catch (e) {
        return Roblox_Util_FastLog_1.FASTLOG2(Roblox_Util_FastLog_1.DFLog('Tasks'), `[DFLog::Tasks] Error: %s, Stack Trace: %s`, e.message, e.stack);
    }
})();
process.stdin.resume();
function exitHandler(options) {
    if (options.exit) {
        if (options.error)
            Roblox_Util_FastLog_1.FASTLOGS(Roblox_Util_FastLog_1.DFLog('Tasks'), `[DFLog::Tasks] %s`, options.message);
        if (options.message)
            Roblox_Util_FastLog_1.FASTLOGS(Roblox_Util_FastLog_1.DFLog('Tasks'), `[DFLog::Tasks] %s`, options.message);
        process.exit();
    }
}
process.on('SIGINT', exitHandler.bind(null, { exit: true, message: 'SIGINT on server' }));
process.on('SIGUSR1', exitHandler.bind(null, { exit: true, message: 'SIGUSR1 on server' }));
process.on('beforeExit', exitHandler.bind(null, { exit: true, message: 'Exit Services' }));
process.on('SIGUSR2', exitHandler.bind(null, { exit: true, message: 'SIGUSR2 on server' }));
process.on('uncaughtException', (e) => {
    exitHandler({ exit: true, error: true, message: `Name: ${e.name}, Reason: ${e.message}, Stack Trace: ${e.stack}` });
});
